### PR TITLE
Typescript rewriting

### PR DESCRIPTION
**Pull request by RemyK888**
- Complete and optimised rewriting of the code
- Readme rewriting
- Using new dependencies: axios
- node-fetch deletion
- Add scripts to package.json

### CODE REVIEW

**Comment by imanimtiyaz20** [comment]
I'll check this later its 2AM rn, and im really sorry for the total mess in my code as im still in the process rewrite the code to my new lyrics api

**Review by imanimtiyaz20 — CHANGES_REQUESTED** [review]
i have a few changes i want to make

- make it auto search from other search engine if one is failed, i think its a nice feature to add directly to the package code instead doing it on our project
- move genius api key to search options
```js
// no need to put genius api key here
const llyrics = new Llyrics();

// instead we move to searchOptions
const response = await llyrics.find({
      song: 'Bohemian Rhapsody',
      engine: { genius: true, musixmatch: true, youtube: true },
      geniusKey: 'YOUR_GENIUS_API_KEY' // Provide the Genius API key here if needed
   });
   ```
- Change to no default search engine if nothing set to true
```js
if (!engine || Object.values(engine).every(value => !value)) {
      throw new Error('No search engine specified.');
    }
```



so here the edited code

```js
import axios from 'axios';
import { version } from '../package.json';

interface SearchOptions {
  /**
   * The song title
   */
  song: string;

  /**
   * The artist
   */
  artist?: string;

  /**
   * Search engine options. The user can enable or disable each search engine.
   */
  engine?: {
    musixmatch?: boolean;
    genius?: boolean;
    youtube?: boolean;
  };

  /**
   * The Genius API key to use for this search (optional)
   */
  geniusKey?: string;
}

interface DefaultResponse {
  /**
   * The artist
   */
  artist: string;

  /**
   * The song title
   */
  title: string;

  /**
   * Used search engine
   */
  engine: string;

  /**
   * Cover URL
   */
  atworkURL: string;

  /**
   * The song lyrics
   */
  lyrics: string;
}

interface MusixMatchResponse extends DefaultResponse {
  /**
   * The Musixmatch id
   */
  id: number;
}

const apiBaseUrl = 'https://lyrics.lewdhutao.my.eu.org';

/**
 * Class symbolizing `Llyrics`
 * @class
 */
export class Llyrics {

  get version(): string {
    return version;
  }

  /**
   * Finds the lyrics of a song.
   * @param {SearchOptions} searchOptions Options to refine your search
   * @returns Promise<DefaultResponse | MusixMatchResponse>
   * @example
   * const llyrics = new Llyrics();
   * const response = await llyrics.find({
   *    song: 'Bohemian Rhapsody',
   *    engine: { genius: true, musixmatch: true, youtube: true },
   *    geniusKey: 'YOUR_GENIUS_API_KEY' // Provide the Genius API key here if needed
   * });
   * console.log(response.artist);
   */
  public async find(searchOptions: SearchOptions): Promise<DefaultResponse | MusixMatchResponse | undefined> {
    const { song, artist, engine, geniusKey } = searchOptions;

    if (!engine || Object.values(engine).every(value => !value)) {
      throw new Error('No search engine specified.');
    }

    const searchEngines = Object.entries(engine).filter(([key, value]) => value === true).map(([key]) => key);

    for (const searchEngine of searchEngines) {
      let fetchResponse;

      switch (searchEngine) {
        case 'youtube':
          fetchResponse = await axios.get(`${apiBaseUrl}/youtube/lyrics`, { params: { title: encodeURIComponent(song) } });
          break;
        case 'musixmatch':
          fetchResponse = await axios.get(`${apiBaseUrl}/musixmatch/lyrics`, {
            params: { title: encodeURIComponent(song), ...(artist && { artist: encodeURIComponent(artist) }) },
          });
          break;
        case 'genius':
          if (!geniusKey) {
            throw new Error('A Genius API key is required to use the Genius search engine.');
          }
          fetchResponse = await axios.get(`${apiBaseUrl}/genius/lyrics`, {
            params: { title: encodeURIComponent(song), api_key: encodeURIComponent(geniusKey) },
          });
          break;
      }

      if (fetchResponse && fetchResponse.data.lyrics !== undefined) {
        return {
          artist: fetchResponse.data.artist_name,
          title: fetchResponse.data.track_name,
          engine: fetchResponse.data.search_engine,
          atworkURL: fetchResponse.data.artwork_url,
          lyrics: fetchResponse.data.lyrics,
        };
      } else {
        continue;
      }
    }
    return undefined;
}}
```

**Comment by RemyK888** [comment]
Changes : 
- Deletion of the class, use of a single function
- Passing the API key as a function parameter
- Addition of the ‘forceSearch’ option corresponding to automatic searching

**Comment by imanimtiyaz20** [comment]
fix a few spelling mistakes + add a few changes now everything looks good

**Review by imanimtiyaz20 — APPROVED** [review]

**Pull request merged**
